services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sahara_mind_app
    ports:
      - '3000:3000'
    env_file:
      - ../env/prod.env
    volumes:
      - ../:/app
    working_dir: /app
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: sahara_mind_postgres
    restart: always
    env_file:
      - ../env/prod.env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
